/**
 * The wiki table of contents (`index.md`) and the append-only log (`log.md`).
 *
 * Index format (Obsidian-friendly tables, machine-parseable):
 *
 *   ## architecture
 *
 *   | Page | Type | Tags | Summary | Updated |
 *   |------|------|------|---------|---------|
 *   | [Auth module](architecture/module-auth.md) | architecture/module | auth core | Owns token validation | 2026-09-19 |
 */
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { todayISO, writeTextAtomic, type WikiLayout } from "./layout.ts";

export interface TocEntry {
	path: string;
	title: string;
	type: string;
	tags: string[];
	summary: string;
	updated: string;
}

const ROW_RE = /^\|\s*\[(.*?)\]\((.*?)\)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$/;

export function parseIndex(text: string): TocEntry[] {
	const entries: TocEntry[] = [];
	for (const line of text.split(/\r?\n/)) {
		const match = line.match(ROW_RE);
		if (!match) continue;
		const [, title, path, type, tags, summary, updated] = match;
		if (path.includes("](")) continue;
		entries.push({
			path: path.trim(),
			title: title.trim(),
			type: type.trim(),
			tags: tags.trim() ? tags.trim().split(/\s+/) : [],
			summary: summary.trim(),
			updated: updated.trim(),
		});
	}
	return entries;
}

function escapeCell(value: string): string {
	return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

export function topicOf(path: string): string {
	const parts = path.split("/");
	return parts.length > 1 ? parts[0] : "general";
}

export function renderIndex(entries: TocEntry[]): string {
	const groups = new Map<string, TocEntry[]>();
	for (const entry of entries) {
		if (entry.path === "index.md" || entry.path === "log.md") continue;
		const topic = topicOf(entry.path);
		const list = groups.get(topic) ?? [];
		list.push(entry);
		groups.set(topic, list);
	}

	const lines: string[] = [
		"# Wiki Index",
		"",
		"> Table of contents for the project knowledge wiki. Generated by jev-wiki; edit pages, not this file.",
		"",
	];
	for (const topic of [...groups.keys()].sort()) {
		const list = groups.get(topic)!.sort((a, b) => a.title.localeCompare(b.title));
		lines.push(`## ${topic}`, "", "| Page | Type | Tags | Summary | Updated |", "|------|------|------|---------|---------|");
		for (const entry of list) {
			lines.push(
				`| [${escapeCell(entry.title)}](${entry.path}) | ${escapeCell(entry.type)} | ${escapeCell(entry.tags.join(" "))} | ${escapeCell(entry.summary)} | ${escapeCell(entry.updated)} |`,
			);
		}
		lines.push("");
	}
	return `${lines.join("\n").replace(/\s+$/, "")}\n`;
}

export function upsertEntries(existing: TocEntry[], updates: TocEntry[]): TocEntry[] {
	const byPath = new Map(existing.map((entry) => [entry.path, entry]));
	for (const update of updates) byPath.set(update.path, update);
	return [...byPath.values()];
}

export async function readIndex(layout: WikiLayout): Promise<TocEntry[]> {
	const path = join(layout.wikiDir, "index.md");
	if (!existsSync(path)) return [];
	return parseIndex(await readFile(path, "utf8"));
}

export async function writeIndex(layout: WikiLayout, entries: TocEntry[]): Promise<void> {
	await writeTextAtomic(join(layout.wikiDir, "index.md"), renderIndex(entries));
}

export function entryFromPage(relPath: string, data: Record<string, unknown>): TocEntry {
	return {
		path: relPath.split("\\").join("/"),
		title: String(data.title ?? relPath),
		type: String(data.type ?? "concept"),
		tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
		summary: String(data.summary ?? "(no summary)"),
		updated: String(data.updated ?? todayISO()),
	};
}

export async function appendLog(layout: WikiLayout, op: string, title: string, details: string[] = []): Promise<void> {
	const path = join(layout.wikiDir, "log.md");
	const header = `## [${todayISO()}] ${op} | ${title}`;
	const block = [header, ...details.map((line) => `- ${line}`), ""].join("\n");
	if (existsSync(path)) {
		const existing = await readFile(path, "utf8");
		await writeTextAtomic(path, `${existing.replace(/\s+$/, "")}\n\n${block}\n`);
	} else {
		await writeTextAtomic(path, `# Wiki Log\n\n${block}\n`);
	}
}

export async function readRecentLog(layout: WikiLayout, limit = 5): Promise<string[]> {
	const path = join(layout.wikiDir, "log.md");
	if (!existsSync(path)) return [];
	const text = await readFile(path, "utf8");
	return text
		.split(/\r?\n/)
		.filter((line) => line.startsWith("## ["))
		.slice(-limit);
}
